### ISSUE TITLE
Dynamic gravatar source is not working

### ISSUE THREAD

**Issue by hazemhagrass** [wallin/angular-gravatar#22]
HI,
I'm wondering why this code is not working:

```
<img class="member" gravatar-src="'{{user.mail}}'" gravatar-size="100" />
```

I changed user mail more times but your directive changes src in the first time only

**Comment by wallin** [comment]
Hi, thanks for reporting. I can't see any code in your issue?

**Comment by hazemhagrass** [comment]
Sorry it is markdown issue

**Comment by wallin** [comment]
have you tried without the single-quotes? ie. `gravatar-src="{{user.mail}}"`

**Comment by hazemhagrass** [comment]
Yes I did but I got the same issue, the problem is IMG SRC is not updated when gravatar-src changed
Sent using CloudMagic
On Tue, Mar 03, 2015 at 5:33 PM, Sebastian Wallin <notifications@github.com> wrote:have you tried without the single-quotes? ie. gravatar-src="{{user.mail}}"

**Comment by wallin** [comment]
Hi again, sorry, was too fast earlier. Try not using an expression, like: `gravatar-src="user.mail"`. This directive is different from the `ng-src` directive in that sense.

Working example
http://jsbin.com/reruxebide/1/edit?html,js,output

**Comment by hazemhagrass** [comment]
It is working now thanks
