### ISSUE TITLE
Can't force update the image

### ISSUE THREAD

**Issue by Calzzetta** [wallin/angular-gravatar#25]
Hi,

I have a profile page on my app and the user data come from Parse.com.
When the page loads, I start a query to get the user data.

Everytime I get the same image: www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?default=identicon&size=96

Checking the script, image loaded is from the email = ""
After the email is updated with a new email but the image continue the same.

I already tried to user $scope.$apply() but nothing change.
If I set the email, the image loads perfectly.

Inspecting the element is possible to see that the email is updated in the "gravatar-src".

Follow part of my code:

JS:
```javascript
var user_parse = Parse.Object.extend("_User");
var query = new Parse.Query(user_parse);
query.get(profile_id, {
  success: function(profile_user) {
    $scope.user_email = profile_user.get("email");
    $scope.$apply();
  },
  error: function(error) {
    toaster.pop('error', 'Error...');
    $scope.$apply();
  }
});
```

HTML:
```html
<img gravatar-src="'{{user_email}}'" gravatar-size="96" class="img-circle">
```

Best regards,
Douglas

**Comment by Calzzetta** [comment]
I found the problem. Just updated the html to:

```html
<img gravatar-src-once="user_email" gravatar-size="96" class="img-circle">
```

Could you please include this "trick" in the "readme"?

Best regards,
Douglas

**Comment by wallin** [comment]
Hi,

I think the problem you had was because you set `gravatar-src="'{{email}}'"`. You should use the scope variable directly (as you did in the second post), ie. `gravatar-src="email"`

By using `gravatar-src-once` the image will only update once

Hope this helps
