### ISSUE TITLE
gravatar not workin on cordova

### ISSUE THREAD

**Issue by gimox** [wallin/angular-gravatar#26]
it work on ios emulator and in browser but not load image in a cordova app.
any help?

(no error log)

**Comment by wallin** [comment]
Hi. Would it be possible for you to provide  example code that reproduces the problem?

**Comment by gimox** [comment]
it's difficult.
I use same example code, that work perfect in all browser, in ios emulator with ionic/cordova but when i compile the app, it not resolve image.

**Comment by wallin** [comment]
I see. I haven't used Cordova so I haven't got any idea of what might cause the problem. A sample project illustrating the problem would be a good start

**Comment by gimox** [comment]
can be somethink about htt / image policy restriction... i'm working on it

**Comment by fiznool** [comment]
@gimox you might need to configure Cordova to allow access to the gravatar domain: http://cordova.apache.org/docs/en/5.0.0/guide_appdev_whitelist_index.md.html#Whitelist%20Guide

**Comment by gimox** [comment]
you right!!! thanxs i try now...

**Comment by gimox** [comment]
i check my config.xml and i have   <access origin="*"/>.

mm this is not the solution...

**Comment by fiznool** [comment]
Did you follow these instructions? https://github.com/wallin/angular-gravatar#configuration

> For example, if you are developing a mobile app with Cordova you should use http. Otherwise directive will use file protocol and fail.

**Comment by gimox** [comment]
ok i found the solution:
https://github.com/apache/cordova-plugin-whitelist

**Comment by wallin** [comment]
Ok. I'll close this issue. 
If you want, please add a note about that in the README

**Comment by thaiat** [comment]
Hi @gimox can you explain your solution ? i'm having the same issue

**Comment by samuelcastro** [comment]
Hi guys. When I try to use the angular-gravatar in my ionic app I'm getting this issue:

Failed to load resource: net::ERR_FILE_NOT_FOUND file://www.gravatar.com/avatar/...

**Comment by wallin** [comment]
Hi @samuelcastro, did you try setting `gravatarServiceProvider.protocol = 'http';` as described in the README? https://github.com/wallin/angular-gravatar#configuration

**Comment by samuelcastro** [comment]
Hi @wallin, worked perfectly thank you, I didn't see that option. :)
