### ISSUE TITLE
Default images without network access

### ISSUE THREAD

**Issue by LiamK** [wallin/angular-gravatar#28]
Hi --

In some cases my application needs to run on an intranet, where it does not have network access to the gravatar site, and thus no gravatars or generated default images.
In that situation I still prefer to serve up an image of some kind.  Leaving out the image messes up the layout.  I could do this in the code for each place I'm using angular-gravatar.  But I would really rather have angular-gravatar do it.

Using a single locally accessible default image would be satisfactory.  Is this do-able?

Alternatively, with a bit more work I could see creating a graphic (or a div) that had a colored background and the first letter of the user's name.

Any advice/help?

**Comment by wallin** [comment]
Hi,

Thanks for your feedback. I like the idea of having a way of setting a fallback image. I see a two ways of achieving this:

1. Specifying a fallback image in default options or per image options and display that in case the image fails to download from Gravatar.
2. Make the url-generating function override:able, to be able to return any string you want. In your case, you could configure the app differently when running it locally without internet access.

Both of these could be useful, depending on the use-case. What do you think?

**Comment by LiamK** [comment]
Sebastian,

Thanks for your reply.  I agree that both of your ideas would be useful.

In this case, I actually don't want it to even try to get the image from
Gravatar.  No point doing that if I know the network is not available. 
(Technically, it is available but unreliable in this circumstance.)

I guess for my case #2 is better.  Is this something your team could add?

Liam

**Comment by wallin** [comment]
I'll see if I can look into it next week. But feel free to contribute and I'll happily review and accept pull-requests

**Comment by wallin** [comment]
I just pushed version `0.4.0` which allows you to override the URL. Check it out.

Closing this issue now

**Comment by LiamK** [comment]
Thanks!
