### ISSUE TITLE
Need help with urlFunc

### ISSUE THREAD

**Issue by LiamK** [wallin/angular-gravatar#29]
Hi --

I have this *almost* working!  Thanks for implementing it.  The thing I've run into is that it looks like I need to duplicate the default code for those cases when I just want the standard behavior.
This works, but the code depends on the angular-gravatar md5 module. 
(Currently this is working for me, since hashRegex returns true in my case.)
I'm not sure how to include it -- adding it as a provider fails -- or if this is the best approach.
Any ideas how to deal with this?

I can't put the check for $preloaded.kiosk outside the definition of urlFunc, so that I leave urlFunc undefind -- I tried that.  It is always false.

```javascript
gravatarServiceProvider.urlFunc = function (opts) {
        if ($preloaded.kiosk){
            return '/static/project/img/embrace_gravatar.jpg';
        }
        else {
            // This code duplicates what is in angular-gravatar.js
            var params, pieces, prefix, src, urlBase, hashRegex, serialize;
            hashRegex = /^[0-9a-f]{32}$/i;

            serialize = function(object) {
                var k, params, v;
                params = [];
                for (k in object) {
                    v = object[k];
                    params.push("" + k + "=" + (encodeURIComponent(v)));
                }
                return params.join('&');
            };
            prefix = opts.protocol ? opts.protocol + ':' : '';
            urlBase = opts.secure ? 'https://secure' : prefix + '//www';
            src = hashRegex.test(opts.src) ? opts.src : md5(opts.src);
            pieces = [urlBase, '.gravatar.com/avatar/', src];
            params = serialize(opts.params);
            if (params.length > 0) {
                pieces.push('?' + params);
            }
            return pieces.join('');
        }
    };
```

**Comment by LiamK** [comment]
It seems like having the urlFunc in the run block instead of the configuration block might work better.  Is that possible?
Then I could do something simple like
```javascript
if ($preloaded.kiosk) {
    gravatarProvider.urlFunc = function () {
         return '/static/project/img/embrace_gravatar.jpg';
     }
}
```

**Comment by wallin** [comment]
Oh, good point. I've pushed `0.4.1` which allows you to either inject `md5` into the provider. Or now you can just save a reference to the old `urlFunc` before overriding it and then call that function instead depending on the value of  `$preloader.kiosk`

**Comment by LiamK** [comment]
It works! Thanks so much for you help :-)

```javascript
 var stdUrlFunc = gravatarServiceProvider.urlFunc;
    gravatarServiceProvider.urlFunc = function (opts) {
        if ($preloaded.kiosk){
            return '/static/project/img/embrace_gravatar.jpg';
        }
        else {
            return stdUrlFunc(opts);
        }
    };
```

**Comment by wallin** [comment]
Cool! glad to help
