### ISSUE TITLE
Need an intercept for user data delivered as a promise

### ISSUE THREAD

**Issue by jmsherry** [wallin/angular-gravatar#32]
Hi there,
My user data is delivered as a promise and the directive executes before it is delivered. Is there any way to trigger the directive to see the change?

Thanks

James

**Comment by wallin** [comment]
Hi, could you give me an example on how that code works, both JS and markup? I'm not sure I understand how the data is set.

**Comment by jmsherry** [comment]
Sure. :)

// Service
`$resource('api/users/1').get(function($user){return $user});`

// Controller

`var vm - this, $user = Users.get();
$q.when($user, function(user){
 vm.user = user 
});

return vm;`

//your gravatar directive template
`<img gravatar-src="'{{vm.user.email}}'" gravatar-size="100" height="100" width="100" ng-cloak>`

As you can see, vm.user gets defined later and is either undefined (if as above) or if a promise...

**Comment by wallin** [comment]
Oh, you're not the first one to do this, but you shouldn't use a template in `gravatar-src` but rather the model itself. Ie. `gravatar-src="vm.user.email"`

Just out of curiosity, what was it that made you think that you need a template? the README?
Would it make more sense to call the attribute `gravatar-model`?

**Comment by jmsherry** [comment]
Ah, thank you!

I think I just misread the README whilst coding too late at night! I looked at the README now and it seems clear enough...

Thanks Sebastian... :)
