### ISSUE TITLE
Angular 1.5 support

### ISSUE THREAD

**Issue by niemyjski** [wallin/angular-gravatar#39]
I've been using this with angular 1.5 with no issues. Can you please bump the bower allowed version to <2.0

**Comment by wallin** [comment]
Thanks! I updated the bower dependencies and pushed `0.4.2`

**Comment by niemyjski** [comment]
Can you please push a new release so bower will pick up the changes.

**Comment by wallin** [comment]
Crap, forgot to push the tag. It's done now. Thanks!
