### ISSUE TITLE
Inject html code from controller

### ISSUE THREAD

**Issue by ysilvela** [wallin/angular-gravatar#41]
Its impossible to see the gravatar image if I inject the html code directly from the controller. I need to do  this because part of the page is built in the controller.

Please, there are any method to see the gravatar image injecting the code?

Thanks.

**Comment by wallin** [comment]
Hi, if you want to manually generat the source you can include the `gravatarService` in your controller and call `var url = gravatarService.url('email@example.com');` to get the URL to the image.

Let me know if this solves your problem

**Comment by wallin** [comment]
@ysilvela How did it work out? ok to close this?

**Comment by ysilvela** [comment]
Yes. Close it!!

Thanks a lot!!!

2016-05-09 20:17 GMT+02:00 Sebastian Wallin <notifications@github.com>:
