### ISSUE TITLE
Lexer Error

### ISSUE THREAD

**Issue by spaceghostu** [wallin/angular-gravatar#42]
Lexer Error: Unexpected next character  at columns 13-13 [@] in expression

**Comment by spaceghostu** [comment]
changed <img gravatar-src="{{vm.loggedInUser.email}}">
to <img gravatar-src=" ' {{vm.loggedInUser.email}} ' ">

**Comment by wallin** [comment]
Hi, could you give a more detailed description to the problem you're seeing? A complete example would help

**Comment by spaceghostu** [comment]
adding the inverted commas fixed the problem, i think angular was reading the email address as an expression rather than a string

**Comment by wallin** [comment]
actually, you can just do: `gravatar-src="vm.loggedInUser.email"`

ok to close this?
