### ISSUE TITLE
angular-gravatar@0.4.1 requires a peer of grunt-cli@0.1.13 but none was installed.

### ISSUE THREAD

**Issue by beeman** [wallin/angular-gravatar#43]
Hi @wallin,

I'm using angular-gravatar in my project [loopback-angular-admin](https://github.com/beeman/loopback-angular-admin) which I'm migrating to using `npm` instead of `bower`. I'm also using `gulp` instead of `grunt`. 

When installing the npm version I get the warning: `angular-gravatar@0.4.1 requires a peer of grunt-cli@0.1.13 but none was installed.`. 

I was curious if this is really needed?

Regards Bram

**Comment by wallin** [comment]
Hi @beeman, you project looks really cool! well done!

Yeah, I believe that dependency can definitely be removed. This project shouldn't depend on anything but Angular. Feel free to do a PR

**Comment by beeman** [comment]
Hey @wallin, thanks a lot for your kind words!

I have just submitted a PR that removes the peerDependency to the devDependency and adds a regular dependency to Angular, version 1.2.5 and above (I've tested with this version).

**Comment by wallin** [comment]
Merged! Thanks @beeman
