### ISSUE TITLE
Gravatar Failed - GravatarServiceProvider

### ISSUE THREAD

**Issue by CBox** [wallin/angular-gravatar#45]
Hi,

I'm using AngularJS V1.6.3

The error I'm getting:
Error: [$injector:modulerr] Failed to instantiate module ui.gravatar due to:
Error: [$injector:unpr] Unknown provider: gravatarServiceProvider

How can I fix that?

Thanks!

**Comment by wallin** [comment]
Hello, could you create a jsbin or similar that recreates the problem?

Thanks

**Comment by CBox** [comment]
Hey,

I've loaded UI Gravtar from Bower and I've changed it to NPM and it's working now but I'm gettings this error:
Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 8-8 [@] in expression [onlyserv@gmail.com].

onlyserv@gmail.com is my real email address, why is it?

Thanks!

**Comment by thewarpaint** [comment]
Hey,

I think it's better if you provide the JSBin example. Looking at the code
it seems like you're missing the quotes around the email. But the example
can make debugging easier.

**Comment by CBox** [comment]
I've also try it like this:
`<img gravatar-src="'{{ contact.email }}'">`

Didn't help :/

**Comment by CBox** [comment]
Sorry about it, the quotes fixed the problem, I have the code in 2 places, on with and one without.
Thanks a lot!

**Comment by wallin** [comment]
Glad it worked out!
